### ISSUE TITLE
您好，请问这个百度编辑器有成功上传图片的小例子吗？

### ISSUE THREAD

**Issue by hongyu2016** [uedkx/think-ueditor#2]
我用的时候总是报500错误
const ThinkUeditor=require('think-ueditor');
const Base = require('./base.js');
module.exports = class extends Base {

uploadimageAction(){
        //百度编辑器
        const ueditor = new ThinkUeditor(this.ctx);
        this.json(ueditor.init());
   }

}

控制器 我是这么写的。
// 服务器统一请求接口路径
 , serverUrl: URL+'../../../news/uploadimage'    前端的配置文件也这么写了，并没有报配置的错误。

有没有可以用小例子参考下呢？谢谢啦？971976839@qq.com 可以发给我邮箱吗

**Comment by q1998763** [comment]
能发下报错信息吗

**Comment by hongyu2016** [comment]
我已经找到解决方法了。。。
